### ISSUE TITLE
Overview of HOPR transfers on xDai

### ISSUE THREAD

**Issue by QYuQianchen** [hoprnet/hopr-analytics#1]
_The following is an issue for bounty, meant for external contributors to pick up and work on the analytics of HOPR tokens._
_Click [here](https://gitcoin.co/hoprnet) to check all the bounties and [here](https://hoprnet.jobbase.io/) to check all the open positions at HOPR._

# Introduction
Recently our community has launched a [three-phase token distribution](https://medium.com/hoprnet/the-hopr-token-launch-5afed592b741) on xDai chain and Ethereum blockchain at the end of February 2021. More than 30,000 of transactions were generated from various decentralized exchanges (DEX) since the launch. The HOPR token was even ranked as one of the top 20 tokens by trading volume on CoinMarketCap. 

From the vast public data, we want to get a better understanding of HOPR trading activities. We invite you to explore the public Ethereum and xDai chain and provide answers to the following questions with source code and visualizations. 

[HOPR token](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da) was deployed on [Ethereum mainnet](https://etherscan.io/tx/0x767782e2dd45f4dc4599921c3e6a4ffb42b9d6c1fcb6fd5aa86976971f3b83b9) on the 19th Feb. Shortly after the deployment, 85 million HOPR were minted for the token launch. 50 million out of the 85 million were pre-sale (1st phase of token launch) tokens that were [bridged to xDai chain](https://blockscout.com/xdai/mainnet/address/0xD057604A14982FE8D88c5fC25Aac3267eA142a08/transactions) for HOPR Genesis DAO members to purchase. HOPR Genesis DAO members are accounts that hold [gHOP tokens](https://blockscout.com/xdai/mainnet/address/0x67E9540b33f8d8c07169bccA3F1b8f5e6cF6f9F3/transactions). Those presale tokens have a locking period until almost the end of the [Balancer LBP sale](https://medium.com/hoprnet/hopr-launch-phase-2-balancer-liquidity-bootstrapping-pool-7128c7ce5896) (2nd phase of token launch). DAI collected from presale and the remainder of pre-sale tokens were bridged back to Ethereum mainnet to be put into the [Balancer LBP sale pool](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da), together with the 30 million HOPR tokens planned for the 2nd phase of token launch. Towards the end of the LBP sale, pre-sale tokens were unlocked on the xDai chain. All the DAI and HOPR staying in the LBP pool were transferred to Uniswap for the 3rd phase of token launch. Those tokens were the initial liquidity providers for the [HOPR/DAI pair](https://etherscan.io/token/0x92c2fc5f306405eab0ff0958f6d85d7f8892cf4d). This pool remains open.

Besides the 85 million token launch, there are around 13.3 million circulating HOPR tokens later minted for bounties ([bridged to xDai](https://etherscan.io/tx/0xe9a2803782d229995d0dbe2906b94d5359b103d990ca943c80f27ec9698aabd8)) and 31.9 million tokens [minted](https://etherscan.io/tx/0x3a229ca7001ffb25f1ae77d41ce2f18bcd7deabfa564aa3aba1c8153834bb916) for treasury. 

Some analytics has been done for the LBP sale part of HOPR token launch. [See the dashboard here](https://duneanalytics.com/qyuqianchen/lbp-sale).

# Task Description
Due to the cross-chain nature of HOPR tokens (living both on Ethereum mainnet and xDai chain), we would like to gain a bird view on the HOPR token transfers on both chains: 

1. Visualize life-cycle (provenance) of xHOPR in a network graph: 
                a. Token minted by OmniBridge (bridging from Ethereum Mainnet)
                b.  Distribution/Transfer/Trading activities with EOAs/contracts (e.g. “[HoprPresale](https://blockscout.com/xdai/mainnet/address/0x9Fea9a2f645D08866e972935595f393BdDff0749/transactions)”, Pancake swap, “[HoprDistributor](https://blockscout.com/xdai/mainnet/address/0x987cb736fBfBc4a397Acd06045bf0cD9B9deFe66/transactions)”)
  c. Token burnt by OmniBridge (bridging back to Ethereum Mainnet)

# Definition of complete

- [ ] A working Nodejs project or python project or with another data analytics platform (e.g. DuneAnalytics/BigQuery) that contains scripts/queries that extracts HOPR transfers on Ethereum mainnet and xDai chain. Instruction on installation and running should be well-documented.
- [ ] Visualize xHOPR token transfers in a network graph, where a node represents an Ethereum address and a directional edge denotes a token transfer. The amount of tokens being transferred and the timestamp of the transfer is labeled on the edge.

# Useful sources
- [HOPR price](https://coinmarketcap.com/currencies/hopr/ )
- [HOPR markets](https://coinmarketcap.com/currencies/hopr/markets/ )
- [General information on HOPR token](https://hoprnet.org/token)
- Contracts:
  - [HOPR token](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da )
  - [xHOPR](https://blockscout.com/xdai/mainnet/address/0xD057604A14982FE8D88c5fC25Aac3267eA142a08/transactions )
  - [HOPR presale](https://blockscout.com/xdai/mainnet/address/0x9Fea9a2f645D08866e972935595f393BdDff0749/transactions)
  - [HOPR LBP](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da)
  - [HOPR/DAI UNI pool](https://etherscan.io/token/0x92c2fc5f306405eab0ff0958f6d85d7f8892cf4d)
  - [HOPR Farm](https://etherscan.io/address/0x2fc0e2cfe5d6ea300d555e5907319a5f7e09884f)
- [Twitter API](https://developer.twitter.com/en/docs/twitter-api )
- Analytics dashboards
  - [Phase 2 - LBP](https://duneanalytics.com/qyuqianchen/lbp-sale)
  - [Liquidity mining - Farm](https://duneanalytics.com/qyuqianchen/Farm)
- [HOPR medium blog](https://medium.com/hoprnet )
  - [Analysis on Presale](https://medium.com/hoprnet/hopr-presale-analysis-3201eb66c20b)
  - [Analysis on LBP](https://medium.com/hoprnet/the-hopr-sale-on-lbp-8bed992d058c)
  - [Breakdown on cost and schedule of HOPR farm](https://medium.com/hoprnet/the-hopr-farm-should-you-join-the-harvest-96f9936d0dae)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 400.0 HOPR (236.52 USD @ $0.59/HOPR)  attached to it as part of the hoprnet fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,976,277.86 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 265 years, 6 months from now.
Please review their action plans below:


**1) [d10-cat](https://gitcoin.co/d10-cat) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?mutate_worker_action=approve&worker=d10-cat) | [reject worker](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?mutate_worker_action=reject&worker=d10-cat))_.**

To start I will take care of the cross chain issue using dedicated smart contracts with designated in total of atleast 3 smart contracts for transactions verification validation which eliminates double spending attempts. Next I will overview the separate blockchains and give an in depth growth analysis for your hopr token. As far as I can see with you total treasury holdings versus actively used tokens there is room for massive growth talking width area wise this alone give you opportunities for contributor competitions and other various contests foes the best Dapp if you were to take that direction similar to ThunderCore hub you would be unique of course doing these events would allow your token to be used in a much more wide area which means more active tokens which is more sold we can also add a half fork every quarter fiscal to regain approx 17% of burned tokens told hold in a cloud based highly encrypted token treasury vault where this will act as a wallet with much more space private keys passwords the works 

I believe the totality of my description will increase the use and therefore the sale of your hopr token 83% in 2 fiscal years. Kibbs86er@gmail.com please contact me via email it’s just easier I can develop a few starter apps for extra contribution to give you a starting point as well I hope you succeed

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612).

**Comment by QYuQianchen** [comment]
Devide this bounty into 2. The other half can be found in [issue](https://github.com/hoprnet/hopr-analytics/issues/9)

**Comment by gitcoinbot** [comment]
@longin-imperial Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=100)

**Comment by gitcoinbot** [comment]
@longin-imperial Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=100)

**Comment by gitcoinbot** [comment]
@longin-imperial Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=100)

**Comment by gitcoinbot** [comment]
@longin-imperial Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=100)

**Comment by gitcoinbot** [comment]
@d10-cat Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=100)

**Comment by gitcoinbot** [comment]
@d10-cat Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=100)

**Comment by gitcoinbot** [comment]
@d10-cat Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=100)

**Comment by QYuQianchen** [comment]
Hi @niklr! As you've already included your work on xDAI in your submission for issue #9. Could you please also apply for this bounty?

Also, as your PR #13 is merged and deployed. Could you extend your application and include "the amount of token being transferred per transaction" along with "the number of token transfers"?

**Comment by niklr** [comment]
Hey @QYuQianchen! Thanks for the feedback! I will change the application so that multiple data sources are possible; The Graph, RPC and local JSON. First it will try to get live data from The Graph, if this should fail the app will check if an RPC endpoint is configured and if so use it. In case this should fail as well, the last resort will be local JSON files with stale data (as it is now).

I assume "the amount of token being transferred per transaction" means to label the edges (amount of tokens + timestamp)
and "the number of token transfers" means to label the nodes (address + number of mint/burn/transfer events). If this is not what you mean, let me know. In any case, labels will be tricky performance-wise with so many data points but I will give it a shot! Maybe just display them when zoomed in.

**Comment by niklr** [comment]
Just a short update: I'm currently experimenting with [NetV.js](https://netv.zjuvag.org/) and [Stardust](https://stardustjs.github.io/) to render the network graph with WebGL. So far it looks very promising!

**Comment by gitcoinbot** [comment]
@niklr Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612?snooze=100)

**Comment by niklr** [comment]
![0XVuOK54BW](https://user-images.githubusercontent.com/4712166/119303369-e7b43d80-bc65-11eb-9c50-b9736636992f.gif)


Visualization is almost done. Next will be the integration with TheGraph to extend the transfer information with the actual timestamp.

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__The funding of 400.0 HOPR (115.69 USD @ $0.29/HOPR)  attached to this issue has been approved & issued to @niklr.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/1/100025612)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $1,993,882.49 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by QYuQianchen** [comment]
Thank you @niklr for the amazing work and the [interview](https://twitter.com/hoprnet/status/1400025895428149251?s=20)!
