### ISSUE TITLE
[Bounty] Improve Uniswap analysis (HOPR Farm) on Dune: remove minute-based analysis

### ISSUE THREAD

**Issue by SCBuergel** [hoprnet/hopr-analytics#14]
_The following is an issue for bounty, meant for external contributors to pick up and work on the analytics of HOPR tokens._
_Click [here](https://gitcoin.co/hoprnet) to check all the bounties and [here](https://hoprnet.jobbase.io/) to check all the open positions at HOPR._

# Introduction

Followed by HOPR's [token launch](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da), a 13-week liquidity mining program, "[HOPR Farm](https://hopr-farm.eth.link/)", started at the end of March 2021. HOPR Farm [incentivizes token holders to provide liquidity](https://medium.com/hoprnet/a-simple-guide-to-the-hopr-farm-5m-hopr-rewards-4e6d4e931570) for [HOPR-DAI pair](https://etherscan.io/token/0x92c2fc5f306405eab0ff0958f6d85d7f8892cf4d) on Uniswap V2. The total reward amounts to 5 million HOPR tokens. We have provided a breakdown of its associated transaction costs and the schedule of farm rewarding time [in a blog post](https://medium.com/hoprnet/the-hopr-farm-should-you-join-the-harvest-96f9936d0dae). 

# Task Description
A DuneAnalytics [dashboard on HOPR Farm](https://duneanalytics.com/qyuqianchen/Farm) was created to give an overview on the liquidity mining program. We want to improve this dashboard.
- [ ] Replace the token price calculated from `swap` events with price from `dex.trades`
- [ ] Detail the volume and number of transactions that open and close farms. 

# Definition of complete

- [ ] A working DuneAnalytics dashboard that contains scripts/queries with documentation.
- [ ] Remove the minute-based calculation of token price used in all the queries of the said dashboard and replace them with price from `dex.trades`.
- [ ] Add grouped bar charts that shows the daily `openFarm` and `closeFarm` actions. Use `hopr."HoprFarm_evt_TokenAdded"` for staking `UNI-V2` LP tokens when "opening a farm"  and `hopr."HoprFarm_evt_TokenRemoved"` for removing `UNI-V2` LP tokens when "closing a farm". Values related to "open farm" are positive and those related to "close farm" are negavie.
   - [ ] A grouped bar chart for the number of transactions that "opens" and "closes" farm per day.
   - [ ] A grouped bar chart for the amount of `UNI-V2` LP tokens involved in "opens" and "closes" farm per day.
- [ ] Please add all your source code in `hopr-analytics/query` folder and use [this template ](https://github.com/hoprnet/hopr-analytics/blob/main/.github/PULL_REQUEST_TEMPLATE/query.md) for PR.

# Useful sources
- [HOPR price](https://coinmarketcap.com/currencies/hopr/ )
- [HOPR markets](https://coinmarketcap.com/currencies/hopr/markets/ )
- [General information on HOPR token](https://hoprnet.org/token)
- Contracts:
  - [HOPR token](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da )
  - [HOPR/DAI UNI pool](https://etherscan.io/token/0x92c2fc5f306405eab0ff0958f6d85d7f8892cf4d)
  - [HOPR Farm](https://etherscan.io/address/0x2fc0e2cfe5d6ea300d555e5907319a5f7e09884f)
- Analytics dashboards
  - [Liquidity mining - Farm](https://duneanalytics.com/qyuqianchen/Farm)
- [HOPR medium blog](https://medium.com/hoprnet )
  - [Breakdown on cost and schedule of HOPR farm](https://medium.com/hoprnet/the-hopr-farm-should-you-join-the-harvest-96f9936d0dae)

**Comment by QYuQianchen** [comment]
Detailed description

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 300.0 HOPR (108.69 USD @ $0.36/HOPR)  attached to it as part of the hoprnet fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/14/100025759).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/hoprnet/hopr-analytics/14/100025759).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,568,419.30 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 265 years, 6 months from now.
Please review their action plans below:


**1) [wanwywh](https://gitcoin.co/wanwywh) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/hoprnet/hopr-analytics/14/100025759?mutate_worker_action=approve&worker=wanwywh) | [reject worker](https://gitcoin.co/issue/hoprnet/hopr-analytics/14/100025759?mutate_worker_action=reject&worker=wanwywh))_.**

hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/14/100025759).

**Comment by QYuQianchen** [comment]
Hi @dtcarls Please submit your work on Gitcoin.

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work for 300.0 HOPR (86.59 USD @ $0.29/HOPR) has been submitted by__:

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/14/100025759)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/hoprnet/hopr-analytics/14/100025759).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $1,951,348.37 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__The funding of 300.0 HOPR (51.9 USD @ $0.17/HOPR)  attached to this issue has been approved & issued to @dtcarls.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/14/100025759)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $4,404,941.36 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
