### ISSUE TITLE
[Bounty] Where do Uniswap traders come from? DEX Agregators?

### ISSUE THREAD

**Issue by SCBuergel** [hoprnet/hopr-analytics#16]
_The following is an issue for bounty, meant for external contributors to pick up and work on the analytics of HOPR tokens._
_Click [here](https://gitcoin.co/hoprnet) to check all the bounties and [here](https://hoprnet.jobbase.io/) to check all the open positions at HOPR._

# Task Description
[HOPR-DAI Uniswap pool](https://info.uniswap.org/pair/0x92c2fc5f306405eab0ff0958f6d85d7f8892cf4d) was created on the Feb 28th. We want to know:
- Where do Uniswap trades actually come from? We have already seen a bunch of aggregators like 1inch feeding in there.
- What's the % of txs / volume of that over time and who are the top aggregators? This would give meaningful marketing insights as to what potent communities to tap into and activate with marketing actions.

# Definition of complete
We expect to see a DuneAnalytics dashboard that contains visualizations/queries which provide answers (both table and chart) to all the questions. Please choose appropriate charts for visualization. Here below are the minimum requirements for visualization.
- [ ] Two pie chart that shows the provenance of Uniswaps transactions. One by the number of transactions, and the other by the volume of transactions.
- [ ] A stacked bar chart that shows the percentage of the number of HOPR token swaps per aggregator over time (on a daily basis).
- [ ] A stacked bar chart that shows the percentage of HOPR token swaps volume per aggregator over time (on a daily basis).
- [ ] Please add all your source code in `hopr-analytics/query` folder and use [this template ](https://github.com/hoprnet/hopr-analytics/blob/main/.github/PULL_REQUEST_TEMPLATE/query.md) for PR.

# Useful sources
- [HOPR price](https://coinmarketcap.com/currencies/hopr/ )
- [HOPR markets](https://coinmarketcap.com/currencies/hopr/markets/ )
- [General information on HOPR token](https://hoprnet.org/token)
- Contracts:
  - [HOPR token](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da )
  - [xHOPR](https://blockscout.com/xdai/mainnet/address/0xD057604A14982FE8D88c5fC25Aac3267eA142a08/transactions )
  - [HOPR presale](https://blockscout.com/xdai/mainnet/address/0x9Fea9a2f645D08866e972935595f393BdDff0749/transactions)
  - [HOPR LBP](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da)
  - [HOPR/DAI UNI pool](https://etherscan.io/token/0x92c2fc5f306405eab0ff0958f6d85d7f8892cf4d)
  - [HOPR Farm](https://etherscan.io/address/0x2fc0e2cfe5d6ea300d555e5907319a5f7e09884f)
- [Twitter API](https://developer.twitter.com/en/docs/twitter-api )
- Analytics dashboards
  - [Phase 2 - LBP](https://duneanalytics.com/qyuqianchen/lbp-sale)
  - [Liquidity mining - Farm](https://duneanalytics.com/qyuqianchen/Farm)
- [HOPR medium blog](https://medium.com/hoprnet )
  - [Analysis on Presale](https://medium.com/hoprnet/hopr-presale-analysis-3201eb66c20b)
  - [Analysis on LBP](https://medium.com/hoprnet/the-hopr-sale-on-lbp-8bed992d058c)
  - [Breakdown on cost and schedule of HOPR farm](https://medium.com/hoprnet/the-hopr-farm-should-you-join-the-harvest-96f9936d0dae)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 300.0 HOPR (108.69 USD @ $0.36/HOPR)  attached to it as part of the hoprnet fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/16/100025760).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/hoprnet/hopr-analytics/16/100025760).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,568,462.69 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 265 years, 6 months from now.
Please review their action plans below:


**1) [baldator](https://gitcoin.co/baldator) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/hoprnet/hopr-analytics/16/100025760?mutate_worker_action=approve&worker=baldator) | [reject worker](https://gitcoin.co/issue/hoprnet/hopr-analytics/16/100025760?mutate_worker_action=reject&worker=baldator))_.**

I'd like to help you with this: I have good data analysis experience and I've already worked with DuneAnalytics in the past.
I will provide a working dashboard showing the Uniswaps provenance and I'll create a PR to add it to your repo.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/16/100025760).

**Comment by gitcoinbot** [comment]
@baldator Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/16/100025760?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/16/100025760?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/16/100025760?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/16/100025760?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/16/100025760?snooze=100)

**Comment by gitcoinbot** [comment]
@baldator Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/16/100025760?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/16/100025760?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/16/100025760?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/16/100025760?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/16/100025760?snooze=100)

**Comment by gitcoinbot** [comment]
@baldator Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/16/100025760?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/16/100025760?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/16/100025760?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/16/100025760?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/16/100025760?snooze=100)

**Comment by gitcoinbot** [comment]
@baldator Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/16/100025760?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/16/100025760?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/16/100025760?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/16/100025760?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/16/100025760?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work for 300.0 HOPR (102.62 USD @ $0.34/HOPR) has been submitted by__:

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/16/100025760)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/hoprnet/hopr-analytics/16/100025760).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $1,592,950.05 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__The funding of 300.0 HOPR (86.77 USD @ $0.29/HOPR)  attached to this issue has been approved & issued to @baldator.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/16/100025760)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $1,993,681.27 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
