### ISSUE TITLE
Position of HOPR early adopters (Genesis DAO members)

### ISSUE THREAD

**Issue by QYuQianchen** [hoprnet/hopr-analytics#2]
_The following is a bounty issue, meant for external contributors to pick up and work on the analytics of HOPR tokens._

# Introduction
Recently our community has launched a [three-phase token distribution](https://medium.com/hoprnet/the-hopr-token-launch-5afed592b741) on xDai chain and Ethereum blockchain at the end of February 2021. More than 30,000 of transactions were generated from various decentralized exchanges (DEX) since the launch. The HOPR token was even ranked as one of the top 20 tokens by trading volume on CoinMarketCap. 

From the vast public data, we want to get a better understanding of HOPR trading activities. We invite you to explore the public Ethereum and xDai chain and provide answers to the following questions with source code and visualizations. 

[HOPR token](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da) was deployed on [Ethereum mainnet](https://etherscan.io/tx/0x767782e2dd45f4dc4599921c3e6a4ffb42b9d6c1fcb6fd5aa86976971f3b83b9) on the 19th Feb. Shortly after the deployment, 85 million HOPR were minted for the token launch. 50 million out of the 85 million were pre-sale (1st phase of token launch) tokens that were [bridged to xDai chain](https://blockscout.com/xdai/mainnet/address/0xD057604A14982FE8D88c5fC25Aac3267eA142a08/transactions) for HOPR Genesis DAO members to purchase. HOPR Genesis DAO members are accounts that hold [gHOP tokens](https://blockscout.com/xdai/mainnet/address/0x67E9540b33f8d8c07169bccA3F1b8f5e6cF6f9F3/transactions). Those presale tokens have a locking period until almost the end of the [Balancer LBP sale](https://medium.com/hoprnet/hopr-launch-phase-2-balancer-liquidity-bootstrapping-pool-7128c7ce5896) (2nd phase of token launch). DAI collected from presale and the remainder of pre-sale tokens were bridged back to Ethereum mainnet to be put into the [Balancer LBP sale pool](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da), together with the 30 million HOPR tokens planned for the 2nd phase of token launch. Towards the end of the LBP sale, pre-sale tokens were unlocked on the xDai chain. All the DAI and HOPR staying in the LBP pool were transferred to Uniswap for the 3rd phase of token launch. Those tokens were the initial liquidity providers for the [HOPR/DAI pair](https://etherscan.io/token/0x92c2fc5f306405eab0ff0958f6d85d7f8892cf4d). This pool remains open.

Besides the 85 million token launch, there are around 13.3 million circulating HOPR tokens later minted for bounties ([bridged to xDai](https://etherscan.io/tx/0xe9a2803782d229995d0dbe2906b94d5359b103d990ca943c80f27ec9698aabd8)) and 31.9 million tokens [minted](https://etherscan.io/tx/0x3a229ca7001ffb25f1ae77d41ce2f18bcd7deabfa564aa3aba1c8153834bb916) for treasury. 

Some analytics has been done for the LBP sale part of HOPR token launch. [See the dashboard here](https://duneanalytics.com/qyuqianchen/lbp-sale).

# Task Description
HOPR Genesis DAO consists of people who previously participated in HOPR testnets. They have the privilege of purchasing HOPR tokens during the 1st phase of token launch at a favorable price of 0.05 USD/token. We want to understand the current position of HOPR Genesis DAO members.

1. How many of them hodl their presale tokens? (on both xDai or and Ethereum mainnet)
2. How many of them re-invested in HOPR through other platforms (not restricted to LBP/Uniswap)?
3. How much did they gain/lose? (Transaction gas costs need to be considered, assuming an average ETH price of 1600 DAI/ETH)

# Definition of complete
We expect to see a DuneAnalytics dashboard that contains visualizations/queries which provide answers (both table and chart) to the subquestions. Please choose appropriate charts for visualization. Here below are the minimum requirements for visualization.

- [ ] A table that shows the presale purchased amount (in xHOPR), buy amount in HOPR, sell amount in HOPR, (HOPR->xHOPR) bridged amount, buy amount in xHOPR, sell amount in xHOPR, (xHOPR->HOPR) bridged amount, current HOPR balance, current xHOPR balance, and the sum of the latter two per the Genesis DAO member. 
- [x] A stacked bar that shows the composition of their current balance: xHOPR in color (R:96 G:162 B:160) and HOPR in color (R: 96 G: 101 B:136)
- [x] A table that shows the purchased HOPR/xHOPR per Genesis DAO member. Ideally their trading platforms are also identified. Group those purchases by trading platforms per Genesis DAO member. 
- [x] A histogram on the number of Genesis DAO members of different sizes of buy/sell.
- [x] A table that calculates their effective (volume-averaged) sell price, effective (volume-averaged) buy price, trading profit, denoted in xDAI or DAI. Transaction gas costs need to be considered.
- [x] Scatter plot volume adjusted average buy vs average sell per account. All the ones that profit are above a 45° line.

# Useful sources
- [HOPR price](https://coinmarketcap.com/currencies/hopr/ )
- [HOPR markets](https://coinmarketcap.com/currencies/hopr/markets/ )
- [General information on HOPR token](https://hoprnet.org/token)
- Contracts:
  - [HOPR token](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da )
  - [xHOPR](https://blockscout.com/xdai/mainnet/address/0xD057604A14982FE8D88c5fC25Aac3267eA142a08/transactions )
  - [HOPR presale](https://blockscout.com/xdai/mainnet/address/0x9Fea9a2f645D08866e972935595f393BdDff0749/transactions)
  - [HOPR LBP](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da)
  - [HOPR/DAI UNI pool](https://etherscan.io/token/0x92c2fc5f306405eab0ff0958f6d85d7f8892cf4d)
- [Twitter API](https://developer.twitter.com/en/docs/twitter-api )
- [Dashboard of LBP analytics](https://duneanalytics.com/qyuqianchen/lbp-sale)
- [HOPR medium blog](https://medium.com/hoprnet )
  - [Analysis on Presale](https://medium.com/hoprnet/hopr-presale-analysis-3201eb66c20b)
  - [Analysis on LBP](https://medium.com/hoprnet/the-hopr-sale-on-lbp-8bed992d058c)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 400.0 HOPR (352.56 USD @ $0.88/HOPR)  attached to it as part of the hoprnet fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,945,113.73 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 265 years, 7 months from now.
Please review their action plans below:


**1) [mhrann](https://gitcoin.co/mhrann) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?mutate_worker_action=approve&worker=mhrann) | [reject worker](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?mutate_worker_action=reject&worker=mhrann))_.**

mhrannnnnnnnnnnnnnnnnnnnnnnnnn

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430).

**Comment by gitcoinbot** [comment]
@t0bij Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=100)

**Comment by t0bij** [comment]
@gitcoinbot - yes, got the approval today ;)

**Comment by t0bij** [comment]
@QYuQianchen - my understanding of the definition of complete is that it's mandatory to visualize data from xDai and Ethereum mainnet together in charts and tables. Currently DuneAnalytics has no feature to combine both sources in a single chart or query. It's always either xDai or mainnet. I first thought that I might missed out a feature but a community manager on their Discord confirmed my understanding.

Did you maybe solve a comparable challenge in the past or have a recommendation on how to approach the issue? Maybe it's necessary to prepare separate queries in DuneAnalytics and combine the data outside.

**Comment by QYuQianchen** [comment]
Hey @t0bij ! That's indeed a problem. We didn't really have such a problem in the past, where the exact same array of addresses need to be used across chains. Maybe, just an idea, to build an array that contains all the gHOP users (retrieved from a different query, or inserted manually)
```
SELECT * FROM unnest(ARRAY[
        -- some addresses here
        '097707143e01318734535676cfe2e5cf8b656ae8',
        'f6a78083ca3e2a662d6dd1703c939c8ace2e268d',
        '9fea9a2f645d08866e972935595f393bddff0749'
]) AS list
```
and parse them when using:
```
...
WHERE recipient IN (
            SELECT decode(list, 'hex') FROM list
)
```

**Comment by gitcoinbot** [comment]
@t0bij Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=100)

**Comment by gitcoinbot** [comment]
@t0bij Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=100)

**Comment by t0bij** [comment]
@gitcoinbot I'm still working on it and will submit it for review soon.

**Comment by t0bij** [comment]
@QYuQianchen - you can find a WIP dashboard for data from xDai here: https://duneanalytics.com/t0b/hopr_dao_members_xdai_base

In addition I wrote you a message on TG.

**Comment by gitcoinbot** [comment]
@t0bij Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=100)

**Comment by gitcoinbot** [comment]
@t0bij Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

@t0bij due to inactivity, we have escalated [this issue](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430) to Gitcoin's moderation team. Let us know if you believe this has been done in error!

* [x] reminder (3 days)
* [x] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

@t0bij due to inactivity, we have escalated [this issue](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430) to Gitcoin's moderation team. Let us know if you believe this has been done in error!

* [x] reminder (3 days)
* [x] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430?snooze=100)

**Comment by t0bij** [comment]
@gitcoinbot - the reminders went to my spam but I whitelisted the address now.

I'm still working on the bounty. I added a dashboard for the mainnet. The boards should contain all the data needed for the definition of complete. @QYuQianchen maybe you can have a look before I combine them. I also have some more ideas which aren't in the original list.

xDai: https://duneanalytics.com/t0b/hopr_dao_members_xdai_base
Mainnet: https://duneanalytics.com/t0b/hopr_dao_members_mainnet_base

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work for 400.0 HOPR (243.21 USD @ $0.61/HOPR) has been submitted by__:

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $2,142,121.54 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by t0bij** [comment]
@QYuQianchen - I submitted dashboard https://duneanalytics.com/t0b/DAO-Members

As we discussed earlier DuneAnalytics currently has no feature to combine xDai and mainnet data in a single chart or query. I worked around this issue by a fixed list of DAO members in mainnet queries. Furthermore some queries are semi-automatic. I created 2 queries which export data from mainnet or xDai as JSON:

DAO Members - 02 - JSON Export Mainnet - https://duneanalytics.com/queries/40394
DAO Members - 04 - JSON Export xDai - https://duneanalytics.com/queries/41187

The JSON-output is used as input in queries which are marked as semi-automatic. So refreshing data from the other network requires a manual step.

The ranges in the histograms and the ETH price for the fee calculation are configurable by parameters. Please let me know if you need further information.

**Comment by QYuQianchen** [comment]
> @QYuQianchen - I submitted dashboard https://duneanalytics.com/t0b/DAO-Members
> 
> As we discussed earlier DuneAnalytics currently has no feature to combine xDai and mainnet data in a single chart or query. I worked around this issue by a fixed list of DAO members in mainnet queries. Furthermore some queries are semi-automatic. I created 2 queries which export data from mainnet or xDai as JSON:
> 
> DAO Members - 02 - JSON Export Mainnet - https://duneanalytics.com/queries/40394
> DAO Members - 04 - JSON Export xDai - https://duneanalytics.com/queries/41187
> 
> The JSON-output is used as input in queries which are marked as semi-automatic. So refreshing data from the other network requires a manual step.
> 
> The ranges in the histograms and the ETH price for the fee calculation are configurable by parameters. Please let me know if you need further information.

Hi @t0bij Interesting walk around of the cross-chain issue! While looking at your approach, I'm thinking, if it would be easier to use [Dune's "Labels"](https://duneanalytics.com/queries/41187), which marks accounts with "HOPR genesis DAO member", "HOPR Avado airdrop", etc. 

Then in queries, DAO members' addresses can be retrieved with `WHERE EXISTS` clause.

What do you think?

**Comment by QYuQianchen** [comment]
I just went though all the queries of your dashboard. AMAZING job! Really IMPRESSIVE!

Could you please help me better understand the following:
1.  In "[inflow sources](https://duneanalytics.com/queries/41192/81109)" query, "transfer from other accounts" is not a kind of "source" right? For example, account `0x0f9fF5028ef1Aa963C965632F0Bc113A140e63d2` has received some tokens from other Genesis DAO members. How is it treated?
2. In the "[Base Table](https://duneanalytics.com/queries/41059/80841)" query, are "harmers" taken into account? What if a Genesis DAO member provides liquidity with their HOPR tokens (thus, HOPR tokens get converted to UNI-V2 tokens), is somehow their nominal HOPR balance counted in the table?

**Comment by QYuQianchen** [comment]
Three more cosmetics suggestions (Numbered following the previous comment):

4. Could you please change the dashboard name to "Position of HOPR DAO Members"? (On the dashboard interface -> `Edit` -> `Settings` -> `Dashboard title`)
5. Add tags "HOPR", "Uniswap", "DEX" and "trade"? (On the dashboard interface -> `Edit` -> `Settings` -> `Dashboard tags`)
6. Add a text component that describes the purpose of the dashboard (e.g. [Farm dashboard](https://duneanalytics.com/qyuqianchen/Farm)) (On the dashboard interface -> `Edit` -> `Settings` -> `Add text widget`)

**Comment by t0bij** [comment]
Hi @QYuQianchen, thanks for the feedback and your input. I'll address your points asap. By the end of the week at latest.

**Comment by t0bij** [comment]
Hi @QYuQianchen ,

again, thanks for your valuable feedback. I finally found the time to check it.

First, using Dune's Labels definitely would make things easier for static groups like "HOPR genesis DAO member". Great idea.

Regarding your numbered feedback:

**1)** exactly, transfers from/to other accounts is not part of the final dashboard. In https://duneanalytics.com/t0b/hopr_dao_members_xdai_base I had a look at this, especially in DAO adresses which got additional tokens from other DAO adresses. As I wrote earlier some of these movements look suspicious to me but as it wasn't part of the DoD I decided to skip for now.
**2)** no, the farming is only considered in https://duneanalytics.com/queries/40445/79804. So If somebody put Hopr on the farm it's not longer in the current balance.
**3**) is missing I think or has been removed ;) Your first comment has feedback points 1+2, the second 4-6.
**4)** done
**5)** done
**6)** done

Let me know if you have other points. I also refreshed the queries right now. I also looked a bit into automate this. I played around with an AWS Lambda to execute to launch the JSON export queries and set the result in the queries from other chains. I think it could work but would be quite ugly and fragile because probably some ugly HTML parsing would be involved.

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__The funding of 400.0 HOPR (115.69 USD @ $0.29/HOPR)  attached to this issue has been approved & issued to @t0bij.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/2/100025430)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $1,993,997.36 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
