### ISSUE TITLE
HOPR Price development

### ISSUE THREAD

**Issue by QYuQianchen** [hoprnet/hopr-analytics#3]
_The following is a bounty issue, meant for external contributors to pick up and work on the analytics of HOPR tokens._

# Introduction
Recently our community has launched a [three-phase token distribution](https://medium.com/hoprnet/the-hopr-token-launch-5afed592b741) on xDai chain and Ethereum blockchain at the end of February 2021. More than 30,000 of transactions were generated from various decentralized exchanges (DEX) since the launch. The HOPR token was even ranked as one of the top 20 tokens by trading volume on CoinMarketCap. 

From the vast public data, we want to get a better understanding of HOPR trading activities. We invite you to explore the public Ethereum and xDai chain and provide answers to the following questions with source code and visualizations. 

[HOPR token](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da) was deployed on [Ethereum mainnet](https://etherscan.io/tx/0x767782e2dd45f4dc4599921c3e6a4ffb42b9d6c1fcb6fd5aa86976971f3b83b9) on the 19th Feb. Shortly after the deployment, 85 million HOPR were minted for the token launch. 50 million out of the 85 million were pre-sale (1st phase of token launch) tokens that were [bridged to xDai chain](https://blockscout.com/xdai/mainnet/address/0xD057604A14982FE8D88c5fC25Aac3267eA142a08/transactions) for HOPR Genesis DAO members to purchase. HOPR Genesis DAO members are accounts that hold [gHOP tokens](https://blockscout.com/xdai/mainnet/address/0x67E9540b33f8d8c07169bccA3F1b8f5e6cF6f9F3/transactions). Those presale tokens have a locking period until almost the end of the [Balancer LBP sale](https://medium.com/hoprnet/hopr-launch-phase-2-balancer-liquidity-bootstrapping-pool-7128c7ce5896) (2nd phase of token launch). DAI collected from presale and the remainder of pre-sale tokens were bridged back to Ethereum mainnet to be put into the [Balancer LBP sale pool](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da), together with the 30 million HOPR tokens planned for the 2nd phase of token launch. Towards the end of the LBP sale, pre-sale tokens were unlocked on the xDai chain. All the DAI and HOPR staying in the LBP pool were transferred to Uniswap for the 3rd phase of token launch. Those tokens were the initial liquidity providers for the [HOPR/DAI pair](https://etherscan.io/token/0x92c2fc5f306405eab0ff0958f6d85d7f8892cf4d). This pool remains open.

Besides the 85 million token launch, there are around 13.3 million circulating HOPR tokens later minted for bounties ([bridged to xDai](https://etherscan.io/tx/0xe9a2803782d229995d0dbe2906b94d5359b103d990ca943c80f27ec9698aabd8)) and 31.9 million tokens [minted](https://etherscan.io/tx/0x3a229ca7001ffb25f1ae77d41ce2f18bcd7deabfa564aa3aba1c8153834bb916) for treasury. 

Some analytics has been done for the LBP sale part of HOPR token launch. [See the dashboard here](https://duneanalytics.com/qyuqianchen/lbp-sale).

# Task Description
HOPR token price has stabilized around $0.8 since a few weeks ago. We would like to understand the driving factors of price fluctuations since the day 1 of HOPR token launch.
Price of HOPR token has experienced the following stages as part of the token release plan.
1. Presale: set at $0.05
2. LBP: from $1.92 to $0.66 with LBP HOPR:DAI weights adjusted from 96:4 to 40:60 over three days.
3. [Uniswap](https://info.uniswap.org/pair/0x92c2fc5f306405eab0ff0958f6d85d7f8892cf4d): from $0.81 (Feb 28) to $0.88 (current)

We'd learn more about the impact of external activities on the price. Notably, 
1. Correlation between HOPR price on Uniswap and BTC/ETH price
2. Impact of marketing activities on HOPR price on Uniswap: twitter announcements, blog posts and AMA.
3. In particular, did the tweet shouting out to CZ_binance have an impact on the price? If yes, which period of time did this tweet have the most impact on HOPR price? Identify the period and the associated trading activities.
  1. Are these more small buys than before (visualize the fraction of Uniswap trades with a volume of <$1000, <$2000. <5000, <10k, >=10k in a 100% stacked bar plot with each bar representing 24h trading activities)?
  2. Is this accumulation? So people buying who bought before?
  3. Are they hodlers or flippers? What's their average hodl time?

# Definition of complete
We expect to see a DuneAnalytics dashboard (or a working Nodejs project or python project) that contains visualizations/queries which provide answers (both table and chart) to the subquestions. Please choose appropriate charts for visualization. Here below are the minimum requirements for visualization.

- [ ] A line chart that plots HOPR price and BTC price together.
- [ ] The covariance of the HOPR/BTC price
- [ ] A line chart that plots HOPR price and ETH price together.
- [ ] The covariance of the HOPR/BTC price
- [ ] A price chart (x-axis is time and y-axis is price) where relevant events are marked.
- [ ] A price chart around the time when the tweet to CZ_binance was published. 
- [ ] A table contained trading activities (account, volume, price) impacted by the tweet.
- [ ] A stacked bar of the trader’s accounts that were relevant to the CZ_binance post, to highlight the composition of their trades: “total bought HOPR amount associated with tweet” in RGB (25, 114, 120), “balance before the tweet” in RGB (237, 221, 212),  “total sold HOPR amount associated with the tweet” in RGB (196, 69, 54).
- [ ] Visualize the fraction of Uniswap trades relevant to the CZ_binance post with a volume of <$1000, <$2000. <5000, <10k, >=10k in a 100% stacked bar plot with each bar representing 24h trading activities

# Useful sources
- [HOPR price](https://coinmarketcap.com/currencies/hopr/ )
- [HOPR markets](https://coinmarketcap.com/currencies/hopr/markets/ )
- [General information on HOPR token](https://hoprnet.org/token)
- Contracts:
  - [HOPR token](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da )
  - [xHOPR](https://blockscout.com/xdai/mainnet/address/0xD057604A14982FE8D88c5fC25Aac3267eA142a08/transactions )
  - [HOPR presale](https://blockscout.com/xdai/mainnet/address/0x9Fea9a2f645D08866e972935595f393BdDff0749/transactions)
  - [HOPR LBP](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da)
  - [HOPR/DAI UNI pool](https://etherscan.io/token/0x92c2fc5f306405eab0ff0958f6d85d7f8892cf4d)
- [Twitter API](https://developer.twitter.com/en/docs/twitter-api )
- [Dashboard of LBP analytics](https://duneanalytics.com/qyuqianchen/lbp-sale)
- [HOPR medium blog](https://medium.com/hoprnet )
  - [Analysis on Presale](https://medium.com/hoprnet/hopr-presale-analysis-3201eb66c20b)
  - [Analysis on LBP](https://medium.com/hoprnet/the-hopr-sale-on-lbp-8bed992d058c)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 400.0 HOPR (352.56 USD @ $0.88/HOPR)  attached to it as part of the hoprnet fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/3/100025429).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/hoprnet/hopr-analytics/3/100025429).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,944,761.17 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by javipus** [comment]
Hi! I'm interested in working on this issue. What API would you prefer to pull historical price data from? Also, do you recommend taking the average of several markets to get an overall picture or are you more interested in looking at particular exchanges?

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 265 years, 7 months from now.
Please review their action plans below:


**1) [matwaller](https://gitcoin.co/matwaller) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/hoprnet/hopr-analytics/3/100025429?mutate_worker_action=approve&worker=matwaller) | [reject worker](https://gitcoin.co/issue/hoprnet/hopr-analytics/3/100025429?mutate_worker_action=reject&worker=matwaller))_.**

Hey, this bounty just popped up on my email looks interesting and I would like to contribute to the project.

I have read the description on what you need and I can get started later today.

Mathew

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/3/100025429).

**Comment by QYuQianchen** [comment]
HOPR price can be calculated from Uniswap HOPR-DAI pool, which is the most active pool with the largest liquidity.

**Comment by L-KH** [comment]
@QYuQianchen , I tried to submit my work but I only get the "stop work" button.
here is my submission : https://github.com/L-KH/HOPR-Price

**Comment by seii-saintway** [comment]
![image](https://user-images.githubusercontent.com/3340161/115989719-ab57d800-a5fa-11eb-8659-5bc0e21e1908.png)

**Comment by seii-saintway** [comment]
This is the reason.
![image](https://user-images.githubusercontent.com/3340161/115989768-ed811980-a5fa-11eb-98d6-dcdffa8fcc2f.png)

**Comment by QYuQianchen** [comment]
Token swap data can be extracted with [Uniswap V2 subgraph](https://thegraph.com/explorer/subgraph/uniswap/uniswap-v2). Uniswap provides a [detailed documentation](https://uniswap.org/docs/v2/API/queries/ )

An example query is
```
{
  swaps(
    orderBy: timestamp,
    orderDirection: desc,
    first: 10,
    where: {
      pair: "0x92c2fc5f306405eab0ff0958f6d85d7f8892cf4d",
      timestamp_gte: 1620285600
      timestamp_lte: 1620291900
    }
  ) {
    transaction {
      id
      blockNumber
    }
    timestamp
    sender
    to
    amount0In
    amount1In
    amount0Out
    amount1Out
    amountUSD
  }
}
```

**Comment by L-KH** [comment]
@QYuQianchen , hey, did you check my submission? https://github.com/hoprnet/hopr-analytics/issues/3#issuecomment-826179511

**Comment by gitcoinbot** [comment]
@eleonora0119 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/3/100025429?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/3/100025429?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/3/100025429?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/3/100025429?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/3/100025429?snooze=100)

**Comment by Eleonora0119** [comment]
@QYuQianchen it was a great hint, thank you!

**Comment by Eleonora0119** [comment]
Unfortunately, the HOPR-DAI Uniswap link (https://info.uniswap.org/pair/0x92c2fc5f306405eab0ff0958f6d85d7f8892cf4d) is blank for 2 days :(

**Comment by QYuQianchen** [comment]
Have a try with https://v2.info.uniswap.org/pair/0x92c2fc5f306405eab0ff0958f6d85d7f8892cf4d 
As uniswap V3 is just introduced, the old URL is replaced.

**Comment by seii-saintway** [comment]
* Token Code: POHR
* Goal: To raise the market attention for HOPR.
H ← O ← P － R ’s community token
* Meme: POny is HoRse definitely. HOPR belongs to DAO. POHR belongs to users.

# PIP-1 draft
* Total Volume: 1,000,000,000,000,000 pohr
* Starting Market Cap: 1,000,000 cusd
* Roadmap:
1. Launch ido on bsc or the mobile payment chain celo to publicly sell 500,000,000,000,000 pohrs at a price of 0.000,000,001 cusd/pohr. The 500,000 cusds which are received and another 500,000,000,000,000 pohrs are directly locked to provide liquidity and burned LP private keys.
2. After the hopr mainnet is launched, make a copy as the pohr mainnet.

# PIP-2 draft
* Total Volume: 1,000,000,000,000 pohr
* Starting Market Cap: 1,000 cusd
* Roadmap:
1. Launch ido on bsc or the mobile payment chain celo. 1,000 cusd and 1,000,000,000,000 pohr are directly locked to provide liquidity and then burned LP private key.
2. After the hopr mainnet is launched, make a copy as the pohr mainnet.

# PIP-3 draft
* Total Volume: 1,000,000,000,000,000 pohr
* Starting Market Cap: 1,000,000 cusd
* Roadmap:
1. While hopr is preparing starting the hopr mainnet, fork the code repository and change the consensus protocol. Through miners pledge celo, gradually release pohr. Adopt the same halving mechanism as Bitcoin. The number of pohr for user transaction fees is simultaneously halved to stabilize the fiat currency value of transaction fees.
2. After the hopr mainnet is launched, start the pohr mainnet on bsc or the mobile payment chain celo.

![63B5DBF9-A2D6-49E7-9BBE-19D2A6DB01FF](https://user-images.githubusercontent.com/3340161/117915560-7947b500-b320-11eb-9e42-5034e18adf90.jpeg)

**Comment by gitcoinbot** [comment]
@eleonora0119 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/3/100025429?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/3/100025429?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/3/100025429?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/3/100025429?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/3/100025429?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work for 400.0 HOPR (206.9 USD @ $0.52/HOPR) has been submitted by__:

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/3/100025429)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/hoprnet/hopr-analytics/3/100025429).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $2,236,719.17 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by QYuQianchen** [comment]
@Eleonora0119 Could you please create a pull request (PR) to this folder and provide a minimum description in the `README.md` file?

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__The funding of 400.0 HOPR (147.21 USD @ $0.37/HOPR)  attached to this issue has been approved & issued to @eleonora0119.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/3/100025429)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,835,210.02 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__The funding of 400.0 HOPR (151.28 USD @ $0.38/HOPR)  attached to this issue has been approved & issued to @eleonora0119.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/3/100025429)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,750,365.44 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
