### ISSUE TITLE
HOPR-DAI Uniswap trading patterns

### ISSUE THREAD

**Issue by QYuQianchen** [hoprnet/hopr-analytics#5]
_The following is a bounty issue, meant for external contributors to pick up and work on the analytics of HOPR tokens._

# Introduction
Recently our community has launched a [three-phase token distribution](https://medium.com/hoprnet/the-hopr-token-launch-5afed592b741) on xDai chain and Ethereum blockchain at the end of February 2021. More than 30,000 of transactions were generated from various decentralized exchanges (DEX) since the launch. The HOPR token was even ranked as one of the top 20 tokens by trading volume on CoinMarketCap. 

From the vast public data, we want to get a better understanding of HOPR trading activities. We invite you to explore the public Ethereum and xDai chain and provide answers to the following questions with source code and visualizations. 

[HOPR token](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da) was deployed on [Ethereum mainnet](https://etherscan.io/tx/0x767782e2dd45f4dc4599921c3e6a4ffb42b9d6c1fcb6fd5aa86976971f3b83b9) on the 19th Feb. Shortly after the deployment, 85 million HOPR were minted for the token launch. 50 million out of the 85 million were pre-sale (1st phase of token launch) tokens that were [bridged to xDai chain](https://blockscout.com/xdai/mainnet/address/0xD057604A14982FE8D88c5fC25Aac3267eA142a08/transactions) for HOPR Genesis DAO members to purchase. HOPR Genesis DAO members are accounts that hold [gHOP tokens](https://blockscout.com/xdai/mainnet/address/0x67E9540b33f8d8c07169bccA3F1b8f5e6cF6f9F3/transactions). Those presale tokens have a locking period until almost the end of the [Balancer LBP sale](https://medium.com/hoprnet/hopr-launch-phase-2-balancer-liquidity-bootstrapping-pool-7128c7ce5896) (2nd phase of token launch). DAI collected from presale and the remainder of pre-sale tokens were bridged back to Ethereum mainnet to be put into the [Balancer LBP sale pool](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da), together with the 30 million HOPR tokens planned for the 2nd phase of token launch. Towards the end of the LBP sale, pre-sale tokens were unlocked on the xDai chain. All the DAI and HOPR staying in the LBP pool were transferred to Uniswap for the 3rd phase of token launch. Those tokens were the initial liquidity providers for the [HOPR/DAI pair](https://etherscan.io/token/0x92c2fc5f306405eab0ff0958f6d85d7f8892cf4d). This pool remains open.

Followed by the token launch, a 13-week liquidity mining program, "HOPR Farm", started at the end of March 2021. HOPR Farm [incentivizes token holders to provide liquidity](https://medium.com/hoprnet/a-simple-guide-to-the-hopr-farm-5m-hopr-rewards-4e6d4e931570) for HOPR-DAI pair on Uniswap V2. The total reward amounts to 5 million HOPR tokens. We have provided a breakdown of its associated transaction costs and the schedule of farm rewarding time [in a blog post](https://medium.com/hoprnet/the-hopr-farm-should-you-join-the-harvest-96f9936d0dae). 

Besides the 85 million token launch, there are around 13.3 million circulating HOPR tokens later minted for bounties ([bridged to xDai](https://etherscan.io/tx/0xe9a2803782d229995d0dbe2906b94d5359b103d990ca943c80f27ec9698aabd8)) and 31.9 million tokens [minted](https://etherscan.io/tx/0x3a229ca7001ffb25f1ae77d41ce2f18bcd7deabfa564aa3aba1c8153834bb916) for treasury. 

Some analytics has been done for the 30-million LBP sale part of HOPR token launch ([See the dashboard here](https://duneanalytics.com/qyuqianchen/lbp-sale)) and 5-million HOPR liquidity mining program - HOPR Farm ([See the dashboard here](https://duneanalytics.com/qyuqianchen/Farm)).

# Task Description

HOPR-DAI Uniswap pool was created on the Feb 28th. [Trading](https://info.uniswap.org/pair/0x92c2fc5f306405eab0ff0958f6d85d7f8892cf4d) has been very active since the start. We'd learn more about its pattern. Notably, 
1. Is trading more active on weekdays or weekends?
2. Which day and time has the highest/lowest trading activities according to the number of transactions?
3. Which day and time has the highest/lowest trading activities according to the trading volume?
4. What is the pattern of increase/decrease in the number of trading transactions during a week? 
5. What is the pattern of increase/decrease in the trading volume during a week?

# Definition of complete
We expect to see a DuneAnalytics dashboard (or a working Nodejs project or python project) that contains visualizations/queries which provide answers (both table and chart) to all the questions. Please choose appropriate charts for visualization. Here below are the minimum requirements for visualization.

- [ ] A table that normalizes all the transaction by its time in a week (using UTC time or CET time). 
- [ ] A line chart that plots all the above-mentioned normalized transactions, grouped by week.
- [ ] A grouped histogram that shows the number of trades over a day, a weekday, and a weekend. Each bin represents an hour.
- [ ] A grouped histogram that shows the volume of trades over a day, a weekday, and a weekend. Each bin represents an hour.

# Useful sources
- [HOPR price](https://coinmarketcap.com/currencies/hopr/ )
- [HOPR markets](https://coinmarketcap.com/currencies/hopr/markets/ )
- [General information on HOPR token](https://hoprnet.org/token)
- Contracts:
  - [HOPR token](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da )
  - [xHOPR](https://blockscout.com/xdai/mainnet/address/0xD057604A14982FE8D88c5fC25Aac3267eA142a08/transactions )
  - [HOPR presale](https://blockscout.com/xdai/mainnet/address/0x9Fea9a2f645D08866e972935595f393BdDff0749/transactions)
  - [HOPR LBP](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da)
  - [HOPR/DAI UNI pool](https://etherscan.io/token/0x92c2fc5f306405eab0ff0958f6d85d7f8892cf4d)
  - [HOPR Farm](https://etherscan.io/address/0x2fc0e2cfe5d6ea300d555e5907319a5f7e09884f)
- [Twitter API](https://developer.twitter.com/en/docs/twitter-api )
- Analytics dashboards
  - [Phase 2 - LBP](https://duneanalytics.com/qyuqianchen/lbp-sale)
  - [Liquidity mining - Farm](https://duneanalytics.com/qyuqianchen/Farm)
- [HOPR medium blog](https://medium.com/hoprnet )
  - [Analysis on Presale](https://medium.com/hoprnet/hopr-presale-analysis-3201eb66c20b)
  - [Analysis on LBP](https://medium.com/hoprnet/the-hopr-sale-on-lbp-8bed992d058c)
  - [Breakdown on cost and schedule of HOPR farm](https://medium.com/hoprnet/the-hopr-farm-should-you-join-the-harvest-96f9936d0dae)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 300.0 HOPR (174.96 USD @ $0.58/HOPR)  attached to it as part of the hoprnet fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/5/100025588).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/hoprnet/hopr-analytics/5/100025588).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,988,949.20 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 265 years, 6 months from now.
Please review their action plans below:


**1) [samhar1995](https://gitcoin.co/samhar1995) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/hoprnet/hopr-analytics/5/100025588?mutate_worker_action=approve&worker=samhar1995) | [reject worker](https://gitcoin.co/issue/hoprnet/hopr-analytics/5/100025588?mutate_worker_action=reject&worker=samhar1995))_.**

I would like to this task, I can provide a python program with a gui for the analysis, I do have some questions that needs answering though

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/5/100025588).

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work for 300.0 HOPR (194.86 USD @ $0.65/HOPR) has been submitted by__:

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/5/100025588)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/hoprnet/hopr-analytics/5/100025588).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $2,406,124.40 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by QYuQianchen** [comment]
Hi @Vicky-1207. Thanks for the [submission](https://duneanalytics.com/vickyzyyy/normalized_transactions)! I only have a few cosmetics suggestions: 

1. Could you please change the dashboard name from "normalized_transactions" to "HOPR-DAI Uniswap trading patterns"? (On the dashboard interface -> `Edit` -> `Settings` -> `Dashboard title`)
2. Add tags "HOPR", "Uniswap", "DEX" and "trade"? (On the dashboard interface -> `Edit` -> `Settings` -> `Dashboard tags`)
3. Add a text component that describes the purpose of the dashboard (e.g. [Farm dashboard](https://duneanalytics.com/qyuqianchen/Farm)) (On the dashboard interface -> `Edit` -> `Settings` -> `Add text widget`)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__The funding of 300.0 HOPR (144.29 USD @ $0.48/HOPR)  attached to this issue has been approved & issued to @vicky-1207.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/5/100025588)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $2,088,678.78 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by QYuQianchen** [comment]
Hi @Vicky-1207 your bounty is paid out. To complete close this issue, could you please create a [pull request](https://guides.github.com/activities/hello-world/#pr) to save all your source codes in a subfolder?
