### ISSUE TITLE
HOPR Twitter engagement

### ISSUE THREAD

**Issue by QYuQianchen** [hoprnet/hopr-analytics#7]
_The following is an issue for bounty, meant for external contributors to pick up and work on the analytics of HOPR tokens. _
_Click [here](https://gitcoin.co/hoprnet) to check all the bounties and [here](https://hoprnet.jobbase.io/) to check all the open positions at HOPR._

# Introduction
[HOPR's twitter account ](https://twitter.com/hoprnet) has over 15,000 followers. It is an important news outlet for HOPR to communicate all the update, announcements, community events to the general public. We would like to have a better understanding on how our tweets interact with other accounts.

# Task Description
Please take data from "HOPR twitter activities" in the attachment section and analyze the following:
1. Pattern of Twitter engagement: At which time of the week, a tweet has the most impression and the most retweets/replies.
2. Which type of the content (key words/topic) receives the most engagement (e.g. impression, replies, likes, and retweets)

# Definition of complete
We expect to see a working Nodejs project or python project that contains source code/queries which provide answers (both table and chart) to all the questions. Please choose appropriate charts for visualization. Here below are the minimum requirements for visualization.
- [x] A bar chart that plots engagement (inclu. but not exhaustive: replies, likes, retweets) per tweet
- [x] A line chart that plots engagement (inclu. but not exhaustive: replies, likes, retweets) by day of the week
- [x] A line chart that plots engagement (inclu. but not exhaustive: replies, likes, retweets) by time (with a reasonable time interval) of the day
- [x] Group tweets by topics and plots a bar chart that shows engagement (inclu. but not exhaustive: replies, likes, retweets) per topic 

# Attachments
[HOPR Twitter activities.zip](https://github.com/hoprnet/hopr-analytics/files/6389824/HOPR.Twitter.activities.zip)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 185.0 HOPR (109.39 USD @ $0.59/HOPR)  attached to it as part of the hoprnet fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/7/100025611).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/hoprnet/hopr-analytics/7/100025611).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,970,640.91 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 265 years, 6 months from now.
Please review their action plans below:


**1) [baldator](https://gitcoin.co/baldator) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/hoprnet/hopr-analytics/7/100025611?mutate_worker_action=approve&worker=baldator) | [reject worker](https://gitcoin.co/issue/hoprnet/hopr-analytics/7/100025611?mutate_worker_action=reject&worker=baldator))_.**

Hi,
I'd love to help you with this. As you can see on my GitHub (@baldator) I have Python experience and I've already worked on social media-related projects.
Thank you,
Marco

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/7/100025611).

**Comment by gitcoinbot** [comment]
@veusti75 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/7/100025611?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/7/100025611?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/7/100025611?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/7/100025611?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/7/100025611?snooze=100)

**Comment by veusti75** [comment]
I'm still working on it

**Comment by veusti75** [comment]
> @veusti75 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
> 
> * [x]  reminder (3 days)
> * [ ]  escalation to mods (6 days)
> 
> Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-analytics/7/100025611?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/7/100025611?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/7/100025611?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/7/100025611?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-analytics/7/100025611?snooze=100)

I'm still working on it

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work for 185.0 HOPR (106.62 USD @ $0.58/HOPR) has been submitted by__:

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/7/100025611)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/hoprnet/hopr-analytics/7/100025611).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $2,459,698.92 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by QYuQianchen** [comment]
PR merged #21

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__The funding of 185.0 HOPR (92.35 USD @ $0.5/HOPR)  attached to this issue has been approved & issued to @veusti75.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/7/100025611)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $2,107,002.82 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by QYuQianchen** [comment]
Bounty completed and [paid](https://etherscan.io/tx/0x30d0d1b28f5270e0a27a13a5ebb74b794cefdd93c0408ec3c89083e486841f74).
