### ISSUE TITLE
Overview of HOPR transfers on Ethereum and the bridge

### ISSUE THREAD

**Issue by QYuQianchen** [hoprnet/hopr-analytics#9]
_The following is an issue for bounty, meant for external contributors to pick up and work on the analytics of HOPR tokens._
_Click [here](https://gitcoin.co/hoprnet) to check all the bounties and [here](https://hoprnet.jobbase.io/) to check all the open positions at HOPR._

# Introduction
Recently our community has launched a [three-phase token distribution](https://medium.com/hoprnet/the-hopr-token-launch-5afed592b741) on xDai chain and Ethereum blockchain at the end of February 2021. More than 30,000 of transactions were generated from various decentralized exchanges (DEX) since the launch. The HOPR token was even ranked as one of the top 20 tokens by trading volume on CoinMarketCap. 

From the vast public data, we want to get a better understanding of HOPR trading activities. We invite you to explore the public Ethereum and xDai chain and provide answers to the following questions with source code and visualizations. 

[HOPR token](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da) was deployed on [Ethereum mainnet](https://etherscan.io/tx/0x767782e2dd45f4dc4599921c3e6a4ffb42b9d6c1fcb6fd5aa86976971f3b83b9) on the 19th Feb. Shortly after the deployment, 85 million HOPR were minted for the token launch. 50 million out of the 85 million were pre-sale (1st phase of token launch) tokens that were [bridged to xDai chain](https://blockscout.com/xdai/mainnet/address/0xD057604A14982FE8D88c5fC25Aac3267eA142a08/transactions) for HOPR Genesis DAO members to purchase. HOPR Genesis DAO members are accounts that hold [gHOP tokens](https://blockscout.com/xdai/mainnet/address/0x67E9540b33f8d8c07169bccA3F1b8f5e6cF6f9F3/transactions). Those presale tokens have a locking period until almost the end of the [Balancer LBP sale](https://medium.com/hoprnet/hopr-launch-phase-2-balancer-liquidity-bootstrapping-pool-7128c7ce5896) (2nd phase of token launch). DAI collected from presale and the remainder of pre-sale tokens were bridged back to Ethereum mainnet to be put into the [Balancer LBP sale pool](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da), together with the 30 million HOPR tokens planned for the 2nd phase of token launch. Towards the end of the LBP sale, pre-sale tokens were unlocked on the xDai chain. All the DAI and HOPR staying in the LBP pool were transferred to Uniswap for the 3rd phase of token launch. Those tokens were the initial liquidity providers for the [HOPR/DAI pair](https://etherscan.io/token/0x92c2fc5f306405eab0ff0958f6d85d7f8892cf4d). This pool remains open.

Besides the 85 million token launch, there are around 13.3 million circulating HOPR tokens later minted for bounties ([bridged to xDai](https://etherscan.io/tx/0xe9a2803782d229995d0dbe2906b94d5359b103d990ca943c80f27ec9698aabd8)) and 31.9 million tokens [minted](https://etherscan.io/tx/0x3a229ca7001ffb25f1ae77d41ce2f18bcd7deabfa564aa3aba1c8153834bb916) for treasury. 

Some analytics has been done for the LBP sale part of HOPR token launch. [See the dashboard here](https://duneanalytics.com/qyuqianchen/lbp-sale).

# Task Description
Due to the cross-chain nature of HOPR tokens (living both on Ethereum mainnet and xDai chain), we would like to gain a bird view on the HOPR token transfers on both chains: 

1. Visualize life-cycle (provenance) of HOPR in a network graph:
               a. Minting
               b. Transfer
               c. Burning
2. Visualize the cross-chain xHOPR and HOPR conversion, by combining the previous two visualizations together.

A bounty on analysis of xHOPR can be found [here](https://github.com/hoprnet/hopr-analytics/issues/1).

# Definition of complete

- [x] A working Nodejs project or python project or with another data analytics platform (e.g. DuneAnalytics/BigQuery) that contains scripts/queries that extracts HOPR transfers on Ethereum mainnet and xDai chain. Instruction on installation and running should be well-documented.
- [x] Visualize HOPR token transfers in two network graphs, where a node represents an Ethereum address and a directional edge denotes a token transfer. The amount of tokens being transferred and the timestamp of the transfer is labeled on the edge.
  - [x] One network graph for HOPR on Ethereum chain.
  - [x] A combined graph of both Ethereum and xDAI chains, as if no bridge existed. E.g. a `Mint` event on xDai (from `0x` to `recipient`) is associated with a `Transfer` event (from `sender` to `bridge`) on ETH. In this graph, it should be projected as a transfer from `sender` to `recipient`.
- [x] The network graph is interactive, where: 
  - [x] All the token transfers associated with an account are highlighted when clicking on a node.
  - [x]  Sender and recipient of the transfer is highlighted when clicking on an edge. Ideally, all the succeeding token transfers associated with a given token transfer is also highlighted.  

# Useful sources
- [HOPR price](https://coinmarketcap.com/currencies/hopr/ )
- [HOPR markets](https://coinmarketcap.com/currencies/hopr/markets/ )
- [General information on HOPR token](https://hoprnet.org/token)
- Contracts:
  - [HOPR token](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da )
  - [xHOPR](https://blockscout.com/xdai/mainnet/address/0xD057604A14982FE8D88c5fC25Aac3267eA142a08/transactions )
  - [HOPR presale](https://blockscout.com/xdai/mainnet/address/0x9Fea9a2f645D08866e972935595f393BdDff0749/transactions)
  - [HOPR LBP](https://etherscan.io/token/0xf5581dfefd8fb0e4aec526be659cfab1f8c781da)
  - [HOPR/DAI UNI pool](https://etherscan.io/token/0x92c2fc5f306405eab0ff0958f6d85d7f8892cf4d)
  - [HOPR Farm](https://etherscan.io/address/0x2fc0e2cfe5d6ea300d555e5907319a5f7e09884f)
- [Twitter API](https://developer.twitter.com/en/docs/twitter-api )
- Analytics dashboards
  - [Phase 2 - LBP](https://duneanalytics.com/qyuqianchen/lbp-sale)
  - [Liquidity mining - Farm](https://duneanalytics.com/qyuqianchen/Farm)
- [HOPR medium blog](https://medium.com/hoprnet )
  - [Analysis on Presale](https://medium.com/hoprnet/hopr-presale-analysis-3201eb66c20b)
  - [Analysis on LBP](https://medium.com/hoprnet/the-hopr-sale-on-lbp-8bed992d058c)
  - [Breakdown on cost and schedule of HOPR farm](https://medium.com/hoprnet/the-hopr-farm-should-you-join-the-harvest-96f9936d0dae)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 400.0 HOPR (252.85 USD @ $0.63/HOPR)  attached to it as part of the hoprnet fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/9/100025648).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/hoprnet/hopr-analytics/9/100025648).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $2,193,145.39 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 265 years, 6 months from now.
Please review their action plans below:


**1) [rade212142](https://gitcoin.co/rade212142) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/hoprnet/hopr-analytics/9/100025648?mutate_worker_action=approve&worker=rade212142) | [reject worker](https://gitcoin.co/issue/hoprnet/hopr-analytics/9/100025648?mutate_worker_action=reject&worker=rade212142))_.**

Fyhgujaha usoshsish hsisosheh udishwhso heiebsuei

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/9/100025648).

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work for 400.0 HOPR (260.77 USD @ $0.65/HOPR) has been submitted by__:

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/9/100025648)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/hoprnet/hopr-analytics/9/100025648).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $2,467,554.91 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by QYuQianchen** [comment]
Thanks for the submission! It fulfils all our requirements. We'd like to include some tips for your additional proposal on the subgraph.

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__The funding of 400.0 HOPR (198.58 USD @ $0.5/HOPR)  attached to this issue has been approved & issued to @niklr.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/9/100025648)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $2,224,403.94 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__The funding of 400.0 HOPR (199.68 USD @ $0.5/HOPR)  attached to this issue has been approved & issued to @niklr.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/9/100025648)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $2,101,993.76 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by QYuQianchen** [comment]
Successfully close this bounty.
